USE [master]
GO

/****** Object:  Database [Numberservice]    Script Date: 09.02.2021 18:12:11 ******/
CREATE DATABASE [Numberservice]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Numberservice', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Numberservice.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Numberservice_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Numberservice_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Numberservice].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Numberservice] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Numberservice] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Numberservice] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Numberservice] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Numberservice] SET ARITHABORT OFF 
GO

ALTER DATABASE [Numberservice] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Numberservice] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Numberservice] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Numberservice] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Numberservice] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Numberservice] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Numberservice] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Numberservice] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Numberservice] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Numberservice] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Numberservice] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Numberservice] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Numberservice] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Numberservice] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Numberservice] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Numberservice] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Numberservice] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Numberservice] SET RECOVERY FULL 
GO

ALTER DATABASE [Numberservice] SET  MULTI_USER 
GO

ALTER DATABASE [Numberservice] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Numberservice] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Numberservice] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Numberservice] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Numberservice] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Numberservice] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Numberservice] SET  READ_WRITE 
GO

