USE [master]
GO

/****** Object:  Database [Nummernservice]    Script Date: 18.03.2021 18:37:30 ******/
CREATE DATABASE [Nummernservice]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Nummernservice', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Nummernservice.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Nummernservice_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Nummernservice_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Nummernservice].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Nummernservice] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Nummernservice] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Nummernservice] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Nummernservice] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Nummernservice] SET ARITHABORT OFF 
GO

ALTER DATABASE [Nummernservice] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Nummernservice] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Nummernservice] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Nummernservice] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Nummernservice] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Nummernservice] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Nummernservice] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Nummernservice] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Nummernservice] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Nummernservice] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Nummernservice] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Nummernservice] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Nummernservice] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Nummernservice] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Nummernservice] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Nummernservice] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Nummernservice] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Nummernservice] SET RECOVERY FULL 
GO

ALTER DATABASE [Nummernservice] SET  MULTI_USER 
GO

ALTER DATABASE [Nummernservice] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Nummernservice] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Nummernservice] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Nummernservice] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Nummernservice] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Nummernservice] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Nummernservice] SET  READ_WRITE 
GO


